# ---------------------------
# Kingdom Ark - Jekyll Config
# ---------------------------

# Site settings
title: "Kingdom Ark"
description: "A sanctuary for study, reflection, and inspiration."
url: "https://harmoniza.github.io"
baseurl: "/kingdom-ark"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Include / Exclude
include:
  - "_includes"
  - "_layouts"
exclude:
  - "node_modules"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"

# Plugins
plugins: []

# Navigation
navigation:
  - title: "Home"
    url: "{{ site.baseurl }}/"
  - title: "About"
    url: "{{ site.baseurl }}/about.html"
  - title: "Contact"
    url: "{{ site.baseurl }}/contact.html"
  - title: "Newsletter"
    url: "{{ site.baseurl }}/newsletter.html"
  - title: "Topics"
    url: "{{ site.baseurl }}/topics/index.html"
  - title: "Store"
    url: "{{ site.baseurl }}/store/"
  - title: "Privacy"
    url: "{{ site.baseurl }}/privacy.html"
  - title: "Terms"
    url: "{{ site.baseurl }}/terms.html"
